<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ6dl033\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ6dl033/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJ6dl033.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJ6dl033\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJ6dl033\appProdProjectContainer([
    'container.build_hash' => 'J6dl033',
    'container.build_id' => '08cfcc28',
    'container.build_time' => 1666255865,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ6dl033');
